---
- name: Add whitelisted domains
  include_tasks:
    file: whitelist.yml

- set_fact:
    image: quiq/egress-proxy:1.21.4.1-alpine

# This is separate unprivileged user which is not restricted by iptables
- user:
    name: egress.proxy
    comment: "Egress Proxy"
    uid: 64444
    shell: /usr/sbin/nologin
    group: nogroup
    create_home: no

- name: Create directory
  file: path=/opt/egress-proxy state=directory mode=0750 owner=egress.proxy group=nogroup

- name: Create tmp directory
  file: path=/tmp/egress-proxy state=directory mode=2770 owner=egress.proxy group=nogroup

- name: Add nginx.conf
  template: src=nginx.conf dest=/opt/egress-proxy mode=0640 owner=egress.proxy group=nogroup
  register: nginx_conf

- name: Pull egress proxy image
  command: docker pull "{{image}}"
  register: docker_pull
  changed_when: '"Downloaded newer image" in docker_pull.stdout'

# Default volumes.
- set_fact:
    volumes_to_mount:
      - "/tmp/egress-proxy:/opt/openresty/nginx/tmp"
      - "/opt/egress-proxy:/opt/openresty/nginx/conf:ro"

- name: Create egress-proxy container
  docker_container:
    name: egress-proxy
    labels: {"name": "egress-proxy"}
    image: "{{image}}"
    state: started
    restart_policy: always
    network_mode: host
    read_only: True
    volumes: "{{ volumes_to_mount }}"
  register: nginx_container

- name: Restart egress-proxy
  command: docker restart egress-proxy
  when: (nginx_conf.changed) and not nginx_container.changed

